export const currenciesDB = {
    Euro: {
      code: "EUR",
      label: "EURO",
      conversionRate: 1,
    },
    Usd: {
      code: "USD",
      label: "US Dollar",
      conversionRate: 1.19,
    },
    Gbp: {
      code: "GBP",
      label: "Pound sterling",
      conversionRate: 0.87,
    },
    TL: {
      code: "TRY",
      label: "Turkish Lira",
      conversionRate: 30.48 , //4 nov 2023 :D 
    },
  };